jdbc:
        driverClassName= com.mysql.Driver
        url= jdbc:mysql://127.0.0.1:3306/springboot_test
        username= root
        password= root
server:
        port: 80
logging:
        pattern:
                console: "%d -%msg%n"
        file:
                path: E://log
spring:
        datasource:
                driver-class-name: com.mysql.jdbc.Driver
                url: jdbc:mysql://127.0.0.1:3306/springboot_test
                password: root
                username: root
        redis:
                port: 6379
                host: localhost

mybatis:
        type-aliases-package: cn.learn.pojo
        mapper-locations: classpath:mappers/*.xml
        configuration:
                log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
